name: ironman2211 Profile Stats

on:
  workflow_dispatch:
  schedule:
    # Runs at 00:00AM UTC Every SUNDAY
    - cron: '0 0 * * SUN'

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: barthachijuu/waka-profile-stats@main
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
